### ISSUE TITLE
一些按钮没有响应？

### ISSUE THREAD

**Issue by CKylinMC** [ivarptr/yu-writer.site#63]
![image](https://user-images.githubusercontent.com/11648014/30508630-63376148-9ace-11e7-8ba9-35af6141ad3a.png)
想要新建 Library 时尝试了下，结果发现 "Library for" 开头的选项点击之后不会有反应，尝试了好几次都是这样，最下面的和Wordpress同步以及连接到服务器的按钮也是如此...
win10 复制到了 ProgramFiles(x86)文件夹 已经加过注册表。设置里暂且就改了一个主题。

**Comment by ZhaoTiexiong** [comment]
带 (*) 应该都是还没有实现的功能，期待作者后面慢慢完善~~~

**Comment by hemashushu** [comment]
是的，因为现在还是尝鲜测试版，有些功能还没完成或者还没经过稳定测试就先禁用并标上 * 号

**Comment by CKylinMC** [comment]
@ivarptr 嗯嗯，另外希望可以有选项禁用文件历史功能，或者对于静态博客，把文件历史功能产生的文件集中在一个特定位置，因为我想用来写hexo的博客文章，但是生成的commit.json文件总是被hexo错误的当成文章...

**Comment by hemashushu** [comment]
后一个问题可以试试先删除hexo博客首层目录下的yulib.config文件（假如有的话），然后再到yuwriter里选择new library -
from blog project，这样一来就会集中 resource 了

2017年9月17日 13:47，"CKylinMC" <notifications@github.com>写道：

@ivarptr <https://github.com/ivarptr> 嗯嗯，另外希望可以有选项禁用文件历史功能，或者对于静态博客，
把文件历史功能产生的文件集中在一个特定位置，因为我想用来写hexo的博客文章，但是生成的commit.json文件总是被hexo错误的当成文章...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ivarptr/yu-writer.site/issues/63#issuecomment-330022992>,
or mute the thread
